# Generated by Django 5.2.10 on 2026-01-24 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupplierProfile',
        ),
    ]
