# Generated by Django 5.2.10 on 2026-01-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_supplierprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_accepting_orders',
            field=models.BooleanField(default=True, help_text='Определяет, может ли пользователь принимать заказы.', verbose_name='Принимает заказы'),
        ),
    ]
