# Generated by Django 5.2.10 on 2026-01-25 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_is_accepting_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_accepting_orders',
        ),
    ]
