# Generated by Django 5.2.10 on 2026-01-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(choices=[('cart', 'Корзина'), ('new', 'Новый'), ('confirmed', 'Подтвержден'), ('done', 'Выполнен')], default='new', max_length=20),
        ),
    ]
