# Generated by Django 5.2.10 on 2026-01-17 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='crated_at',
            new_name='created_at',
        ),
    ]
