# Generated by Django 5.2.10 on 2026-01-25 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='is_accepting_orders',
            field=models.BooleanField(default=True),
        ),
    ]
